services:
  psql:
    container_name: aosql-psql
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=aosql
      - POSTGRES_USER=aosql
      - POSTGRES_DB=santa_workshop
    restart: unless-stopped

  pgadmin:
    container_name: aosql-pgadmin
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    volumes:
      - ./data/.pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=fabrice@local.io
      - PGADMIN_DEFAULT_PASSWORD=aosql
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    restart: unless-stopped
